<?php

namespace common\queries;

/**
 * Class ClientQuery
 *
 * @package common\queries
 */
class ClientQuery extends Query
{
    public function oneById(int $id, $byAccountId = true)
    {
        return parent::oneById($id, $byAccountId); // TODO: Change the autogenerated stub
    }
}