<?php

namespace common\queries;

/**
 * Class MasterQuery
 *
 * @package common\queries
 */
class MasterQuery extends Query
{
    /**
     * @param int $id
     * @param bool $byAccountId
     * @return array|null|\yii\db\ActiveRecord
     */
    public function oneById(int $id, $byAccountId = true)
    {
        return parent::oneById($id, $byAccountId); // TODO: Change the autogenerated stub
    }

    /**
     * @param int $id
     * @param bool $byAccountId
     * @return bool
     */
    public function existsById(int $id, $byAccountId = true)
    {
        return parent::existsById($id, $byAccountId); // TODO: Change the autogenerated stub
    }
}