<?php

namespace common\queries;

/**
 * Class SalonQuery
 *
 * @package common\queries
 */
class SalonQuery extends Query
{
    public function oneById(int $id, $byAccountId = true)
    {
        return parent::oneById($id, $byAccountId);
    }

    /**
     * @param int $limit
     * @param int $offset
     * @return array|\yii\db\ActiveRecord[]
     */
    public function allByParams(int $limit, int $offset)
    {
        return $this->byAccountId()
            ->limit($limit)
            ->offset($offset)
            ->all();
    }

    /**
     * @param int $id
     * @param bool $byAccountId
     * @return bool
     */
    public function existsById(int $id, $byAccountId = true)
    {
        return parent::existsById($id, $byAccountId); // TODO: Change the autogenerated stub
    }
}