<?php

namespace common\queries;

/**
 * Class SalonServiceQuery
 *
 * @package common\queries
 */
class SalonServiceQuery extends Query
{
    /**
     * @param int $id
     * @param bool $byAccountId
     * @return array|null|\yii\db\ActiveRecord
     */
    public function oneById(int $id, $byAccountId = false)
    {
        return parent::oneById($id, $byAccountId); // TODO: Change the autogenerated stub
    }

    /**
     * @param array $id
     * @return array|\yii\db\ActiveRecord[]
     */
    public function allById(array $id)
    {
        return $this->byId($id)
            ->byAccountId()
            ->indexBy('id')
            ->all();
    }
}